### ISSUE TITLE
AttributeError: module 'plistlib' has no attribute 'readPlist'

### ISSUE THREAD

**Issue by coveritytest** [phauer/migrate-itunes-to-rhythmbox#27]
Getting this error:

migrate-itunes-to-rhythmbox playlists \
    --itunes_library_xml="~/Documents/itunes/iTunes Music Library.xml" \
    --rhythmbox_playlists_xml="playlists.xml" \
    --source_library_root="D:/Music/" \
    --target_library_root="/home/pha/Music/"
Reading iTunes library in /home/user/Documents/itunes/iTunes Music Library.xml
Traceback (most recent call last):
  File "/home/user/.local/bin/migrate-itunes-to-rhythmbox", line 76, in <module>
    cli()
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/bin/migrate-itunes-to-rhythmbox", line 32, in migrate_playlist
    playlists = itunes_library_reader.read_playlists(expanded_itunes_library_xml)
  File "/home/user/.local/lib/python3.10/site-packages/migrate_itunes_to_rhythmbox/itunes_library_reader.py", line 9, in read_playlists
    library = Library(library_file)
  File "/home/user/.local/lib/python3.10/site-packages/pyItunes/Library.py", line 26, in __init__
    self.il = plistlib.readPlist(itunesxml) #Much better support of xml special characters
AttributeError: module 'plistlib' has no attribute 'readPlist'

**Comment by coveritytest** [comment]
This problem can be solved via https://github.com/phauer/migrate-itunes-to-rhythmbox/issues/24#issuecomment-1008222961.
